# Generated by Django 3.0.2 on 2020-02-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('noteTitle', models.CharField(max_length=255, unique=True)),
                ('noteBody', models.TextField(blank=True)),
            ],
        ),
    ]
